<body>
    <section style="border:1px solid RoyalBlue;">
        <section style="background-color:White; font-family:Georgia;text-align:center">
            <h1 style="color:RoyalBlue">Introduction to Data Science</h1>
            <h2 style="color:RoyalBlue">Dr.	Casey Kennington</h1>
            <h2 style="font-family:Courier; text-align:center;">CS-533</h2>
            <br>
            <h2 style="font-family:Garamond;">Gerardo Caracas Uribe</h2>
            <h2 style="font-family:Garamond;">Student ID: 114104708</h2>
            <h2 style="font-family:Courier;">Homework #3 tabular-numeric-data</h2>
            <hr/>
        </section>
    </section>
</body>

<body>
    <section style="background-color:White; font-family:Georgia;text-align:center">
        <h2 style="font-family:Garamond; color:solid #229954">Unit 21</h2>
        <h3 style="font-family:Garamond;">Creating Arrays</h3>
        <hr/>
    </section>
</body>

In [1]:
import numpy as np
numbers = np.array(range(1,11), copy=True)

In [2]:
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
ones = np.ones([2, 4], dtype=np.float64)

In [4]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
zeros = np.zeros([2,4], dtype=np.float64)

In [6]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
empty = np.empty([2,4], dtype=np.float64)

In [8]:
empty

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
ones.shape

(2, 4)

In [10]:
numbers.ndim

1

In [11]:
zeros.dtype

dtype('float64')

In [12]:
eye = np.eye(3, k=1)

In [13]:
eye

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [14]:
np_numbers = np.arange(2, 5, 0.25)

In [15]:
np_numbers

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 ,
       4.75])

In [16]:
np_numbers = np_numbers.astype(np.int)

In [17]:
np_numbers

array([2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

<body>
    <section style="background-color:White; font-family:Georgia;text-align:center">
        <h2 style="font-family:Garamond; color:solid #229954">Unit 22</h2>
        <h3 style="font-family:Garamond;">Transposing and Reshaping</h3>
        <hr/>
    </section>
</body>

In [18]:
sap = np.array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'])

In [19]:
sap

array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'],
      dtype='<U4')

In [20]:
sap2d = sap.reshape(2,4)

In [21]:
sap2d

array([['MMM', 'ABT', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [22]:
sap3d = sap.reshape(2, 2, 2)

In [23]:
sap3d

array([[['MMM', 'ABT'],
        ['ABBV', 'ACN']],

       [['ACE', 'ATVI'],
        ['ADBE', 'ADT']]], dtype='<U4')

In [24]:
sap2d.T

array([['MMM', 'ACE'],
       ['ABT', 'ATVI'],
       ['ABBV', 'ADBE'],
       ['ACN', 'ADT']], dtype='<U4')

In [25]:
sap3d.swapaxes(1,2)

array([[['MMM', 'ABBV'],
        ['ABT', 'ACN']],

       [['ACE', 'ADBE'],
        ['ATVI', 'ADT']]], dtype='<U4')

In [26]:
sap3d.transpose((0, 2, 1))

array([[['MMM', 'ABBV'],
        ['ABT', 'ACN']],

       [['ACE', 'ADBE'],
        ['ATVI', 'ADT']]], dtype='<U4')

<body>
    <section style="background-color:White; font-family:Georgia;text-align:center">
        <h2 style="font-family:Garamond; color:solid #229954">Unit 23</h2>
        <h3 style="font-family:Garamond;">Indexing and Slicing</h3>
        <hr/>
    </section>
</body>

In [27]:
dirty = np.array([9, 4, 1, -0.01, -0.02, 0.001])
whos_dirty = dirty < 0 # Boolean array, to be used as Boolean index

In [28]:
whos_dirty

array([False, False, False,  True,  True, False])

In [29]:
dirty[whos_dirty] = 0 # Change all negative values to 0

In [30]:
dirty

array([9.e+00, 4.e+00, 1.e+00, 0.e+00, 0.e+00, 1.e-03])

In [31]:
linear = np.arange(-1, 1.1, 0.2)

In [32]:
(linear <= 0.5) & (linear >= -0.5)

array([False, False, False,  True,  True,  True,  True,  True, False,
       False, False])

In [33]:
sap[[1, 2, -1]]

array(['ABT', 'ABBV', 'ADT'], dtype='<U4')

In [34]:
sap2d[:, [1]]

array([['ABT'],
       ['ATVI']], dtype='<U4')

In [35]:
sap2d[:, 1]

array(['ABT', 'ATVI'], dtype='<U4')

<body>
    <section style="background-color:White; font-family:Georgia;text-align:center">
        <h2 style="font-family:Garamond; color:solid #229954">Unit 24</h2>
        <h3 style="font-family:Garamond;">Broadcasting</h3>
        <hr/>
    </section>
</body>

In [36]:
a = np.arange(4)
b = np.arange(1,5)
a + b

array([1, 3, 5, 7])

In [37]:
a*5

array([ 0,  5, 10, 15])

In [38]:
noise = np.eye(4) + 0.01 * np.ones((4,))

In [39]:
noise

array([[1.01, 0.01, 0.01, 0.01],
       [0.01, 1.01, 0.01, 0.01],
       [0.01, 0.01, 1.01, 0.01],
       [0.01, 0.01, 0.01, 1.01]])

In [40]:
noise=np.eye(4) + 0.01 * np.random.random([4, 4])

In [41]:
noise

array([[1.0014723 , 0.0017637 , 0.00352508, 0.00874918],
       [0.00187577, 1.00881076, 0.00381513, 0.00475499],
       [0.00892539, 0.007531  , 1.00532293, 0.0015965 ],
       [0.00940048, 0.0078706 , 0.00671455, 1.00861877]])

<body>
    <section style="background-color:White; font-family:Georgia;text-align:center">
        <h2 style="font-family:Garamond; color:solid #229954">Unit 25</h2>
        <h3 style="font-family:Garamond;">Demystifying Universal Functions</h3>
        <hr/>
    </section>
</body>

In [42]:
stocks = np.array([140.49, 0.97, 40.68, 41.53, 55.7, 57.21, 98.2, 99.19, 109.96, 111.47, 35.71, 36.27, 87.85, 89.11, 30.22, 30.91])

In [43]:
stocks

array([140.49,   0.97,  40.68,  41.53,  55.7 ,  57.21,  98.2 ,  99.19,
       109.96, 111.47,  35.71,  36.27,  87.85,  89.11,  30.22,  30.91])

In [44]:
stocks = stocks.reshape(8,2).T

In [45]:
stocks

array([[140.49,  40.68,  55.7 ,  98.2 , 109.96,  35.71,  87.85,  30.22],
       [  0.97,  41.53,  57.21,  99.19, 111.47,  36.27,  89.11,  30.91]])

In [46]:
fall = np.greater(stocks[0], stocks[1])

In [47]:
fall

array([ True, False, False, False, False, False, False, False])

In [48]:
sap[fall]

array(['MMM'], dtype='<U4')

In [49]:
# Pretend the new MMM quote is missing
stocks[1,0] = np.nan

In [50]:
np.isnan(stocks)

array([[False, False, False, False, False, False, False, False],
       [ True, False, False, False, False, False, False, False]])

In [51]:
# Repair the damage; it can't get worse than this
stocks[np.isnan(stocks)] = 0

In [52]:
stocks

array([[140.49,  40.68,  55.7 ,  98.2 , 109.96,  35.71,  87.85,  30.22],
       [  0.  ,  41.53,  57.21,  99.19, 111.47,  36.27,  89.11,  30.91]])

<body>
    <section style="background-color:White; font-family:Georgia;text-align:center">
        <h2 style="font-family:Garamond; color:solid #229954">Unit 26</h2>
        <h3 style="font-family:Garamond;">Understanding Conditional Functions</h3>
        <hr/>
    </section>
</body>

In [53]:
changes = np.where(np.abs(stocks[1] - stocks[0]) > 1.00, stocks[1]-stocks[0], 0)

In [54]:
changes

array([-140.49,    0.  ,    1.51,    0.  ,    1.51,    0.  ,    1.26,
          0.  ])

In [55]:
sap[np.nonzero(changes)]

array(['MMM', 'ABBV', 'ACE', 'ADBE'], dtype='<U4')

In [56]:
sap[np.abs(stocks[1] - stocks[0]) > 1.00]

array(['MMM', 'ABBV', 'ACE', 'ADBE'], dtype='<U4')

<body>
    <section style="background-color:White; font-family:Georgia;text-align:center">
        <h2 style="font-family:Garamond; color:solid #229954">Unit 27</h2>
        <h3 style="font-family:Garamond;">Aggregating and Ordering Arrays</h3>
        <hr/>
    </section>
</body>

In [57]:
sap[np.abs(stocks[0] - stocks[1]) > np.mean(np.abs(stocks[0] - stocks[1]))]

array(['MMM'], dtype='<U4')

<body>
    <section style="background-color:White; font-family:Georgia;text-align:center">
        <h2 style="font-family:Garamond; color:solid #229954">Unit 28</h2>
        <h3 style="font-family:Garamond;">Treating Arrays as Sets</h3>
        <hr/>
    </section>
</body>

In [58]:
dna = "AGTCCGCAATACAGGCTCGGT"
dna_as_array=np.array(list(dna))

In [59]:
dna_as_array

array(['A', 'G', 'T', 'C', 'C', 'G', 'C', 'A', 'A', 'T', 'A', 'C', 'A',
       'G', 'G', 'C', 'T', 'C', 'G', 'G', 'T'], dtype='<U1')

In [60]:
np.unique(dna_as_array)

array(['A', 'C', 'G', 'T'], dtype='<U1')

In [61]:
np.in1d(["MSFT","MMM","AAPL"], sap)

array([False,  True, False])

<body>
    <section style="border:1px solid RoyalBlue;">
        <section style="background-color:White; font-family:Georgia;text-align:center">
            <h1 style="color:RoyalBlue">Array Differentiator</h1><br/>
            <h2 style="color:RoyalBlue">Section "Your Turn"</h2><br/>
            <h2 style="color:RoyalBlue">Chapter 5</h2><br/>
            <h2 style="color:RoyalBlue">Page: 82</h2><br/>
        </section>
    </section>
</body>

In [62]:
import pandas as pd
import numpy as np
fn = "./dset.csv"

In [63]:
 t = pd.read_csv(fn, sep='\n', delimiter=',')

In [64]:
t

UNITID                                             INSTNM  \
0     100654                           Alabama A & M University   
1     100663                University of Alabama at Birmingham   
2     100690                                 Amridge University   
3     100706                University of Alabama in Huntsville   
4     100724                           Alabama State University   
5     100733                University of Alabama System Office   
6     100751                          The University of Alabama   
7     100760                  Central Alabama Community College   
8     100812                            Athens State University   
9     100830                    Auburn University at Montgomery   
10    100858                                  Auburn University   
11    100937                        Birmingham Southern College   
12    101028             Chattahoochee Valley Community College   
13    101073                          Concordia College Alabama   
14    101116                        South University-Montgomery   
15    101143                 Enterprise State Community College   
16    101161                  Coastal Alabama Community College   
17    101189                                Faulkner University   
18    101240                    Gadsden State Community College   
19    101277               New Beginning College of Cosmetology   
20    101286          George C Wallace Community College-Dothan   
21    101295  George C Wallace State Community College-Hance...   
22    101301     George C Wallace State Community College-Selma   
23    101365                      Herzing University-Birmingham   
24    101435                                 Huntingdon College   
25    101453                      Heritage Christian University   
26    101462  J. F. Drake State Community and Technical College   
27    101471                 J F Ingram State Technical College   
28    101480                      Jacksonville State University   
29    101499                  Jefferson Davis Community College   
...      ...                                                ...   
7123  491109             National American University-Watertown   
7124  491118  National American University-Career Point Coll...   
7125  491127     Little Priest Tribal College - Ho Chunk Centre   
7126  491136                         Empire Beauty School-Tampa   
7127  491145                      Empire Beauty School-Lakeland   
7128  491154                Bard College - Holyoke Microcollege   
7129  491163                          Advanced College-Stockton   
7130  491172                               Academy Di Capelli -   
7131  491181                       Galen College of Nursing-ARH   
7132  491190  The Chicago School of Professional Psychology ...   
7133  491206  Olympian Academy of Cosmetology - Internationa...   
7134  491224    Tricoci University of Beauty Culture-Janesville   
7135  491233                       Unlimited Cosmetology School   
7136  491242      Johnny Matthew's Hairdressing Training School   
7137  491251                  The Culinary School of Fort Worth   
7138  491288             University of Wisconsin-Milwaukee Flex   
7139  491297              University of Wisconsin-Parkside Flex   
7140  491303              University of Wisconsin Colleges Flex   
7141  491312                 Arizona State University at Tucson   
7142  491321  Arizona State University - ASU Colleges at Lak...   
7143  491330        Arizona State University at The Gila Valley   
7144  491349                   Arizona State University at Yuma   
7145  491358   Relay Graduate School of Education - San Antonio   
7146  491367  Relay Graduate School of Education - Dallas-Fo...   
7147  491376  Relay Graduate School of Education - Washingto...   
7148  491385                           Wright Institute (The) -   
7149  491394                                  Edge Tech Academy   
7150  491419          Health Career Institute- Lauder

In [65]:
from math import *

In [66]:
longitud = t['LONGITUD']
latitud = t['LATITUDE']

The longitud and lattitud columns have dirty data on them. In some cases we have a dot "." instead of a number. In order to get the degrees and make an average we should not consider these fields because number one, they don't have numbers, also if we fill them with either 0, max, or mid values, they will bias the end result of the mean, therefore we won't use them for calculation.<br>
Instead we will get an array if indexes for the valid fields and calculate using only them.

In [67]:
validLongitud = np.where(longitud != '.')
validLatitud = np.where(latitud != '.')

Now we will convert the latitud series into numpy<br>
Then before we can do broadcasting, we need to make an multidimentional array, in this case nx1. For this we will reshape the numpy array.

In [68]:
latitudNp = latitud.values
latitudNp = latitudNp.reshape(latitudNp.shape[0],1)


Now we will convert the longitud series into numpy<br>
Then before we can do broadcasting, we need to make an multidimentional array, in this case nx1. For this we will reshape the numpy array.

In [69]:
longitudNp = longitud.values
longitudNp = longitudNp.reshape(longitudNp.shape[0],1)


Now let's convert each one of the longitud and latitud into degrees, minutes and seconds. Let's make a function that returns this

In [70]:
def convertFromDecimalDegreesToDMS(inputData):
    inputData = inputData.reshape(inputData.shape[0],1)
    degreesf = inputData.real.astype(np.float, copy=True, casting='unsafe')
    degrees = degreesf.astype(np.int, copy=True)
    minutesf  = (degreesf - degrees)*60
    minutes = minutesf.astype(np.int, copy=True)
    seconds = (minutesf - minutes) * 60
    return degrees, minutes, seconds

    

In [71]:
degreesLongitud, minutesLongitud, secondsLongitud = convertFromDecimalDegreesToDMS(longitudNp[validLongitud])
degreesLatitud, minutesLatitud, secondsLatitud = convertFromDecimalDegreesToDMS(latitudNp[validLatitud])

In [72]:
longDegMean=int(np.round(degreesLongitud.mean(), decimals=0))
longMinMean=int(np.round(minutesLongitud.mean(), decimals=0))
longsecMean=secondsLongitud.mean()
latDegMean=int(np.round(degreesLatitud.mean(), decimals=0))
latMinMean=int(np.round(minutesLatitud.mean(), decimals=0))
latSecMean=secondsLatitud.mean()

In [73]:
print("The mean longitud is ",abs(longDegMean),"deg",abs(longMinMean),"'",abs(longsecMean),"\"W")

The mean longitud is  90 deg 29 ' 29.664484859002272 "W


In [74]:
print("The mean latitude is ",abs(latDegMean),"deg",abs(latMinMean),"'",abs(latSecMean),"\"N")

The mean latitude is  37 deg 30 ' 30.213822299349147 "N


<body>
    <section style="background-color:White; font-family:Georgia;text-align:center">
        <h3 style="font-family:Garamond;">In the image below, you can see in the red drop mark, where our average is located
        </h3>
        <hr/>
    </section>
</body>

![title](coordinates.png)

In [75]:
#zeros = list(np.zeros([t.shape[0]], dtype=np.int))
zeros = np.zeros([t.shape[0]], dtype=np.int)
degreesLongitud = degreesLongitud[:,0]
zeros[validLongitud]=degreesLongitud
zeros = zeros.tolist()
t['degreesLongitud'] = pd.Series(zeros, index=t.index)

zeros = np.zeros([t.shape[0]], dtype=np.int)
minutesLongitud = minutesLongitud[:,0]
zeros[validLongitud]=minutesLongitud
zeros = zeros.tolist()
t['minutesLongitud'] = pd.Series(zeros, index=t.index)

zeros = np.zeros([t.shape[0]], dtype=np.int)
secondsLongitud = secondsLongitud[:,0]
zeros[validLongitud]=secondsLongitud
zeros = zeros.tolist()
t['secondsLongitud'] = pd.Series(zeros, index=t.index)

zeros = np.zeros([t.shape[0]], dtype=np.int)
degreesLatitud = degreesLatitud[:,0]
zeros[validLatitud]=degreesLatitud
zeros = zeros.tolist()
t['degreesLatitude'] = pd.Series(zeros, index=t.index)

zeros = np.zeros([t.shape[0]], dtype=np.int)
minutesLatitud = minutesLatitud[:,0]
zeros[validLatitud]=minutesLatitud
zeros = zeros.tolist()
t['minutesLatitud'] = pd.Series(zeros, index=t.index)

zeros = np.zeros([t.shape[0]], dtype=np.int)
secondsLatitud = secondsLatitud[:,0]
zeros[validLatitud]=secondsLatitud
zeros = zeros.tolist()
t['secondsLatitud'] = pd.Series(zeros, index=t.index)

In [76]:
t

UNITID                                             INSTNM  \
0     100654                           Alabama A & M University   
1     100663                University of Alabama at Birmingham   
2     100690                                 Amridge University   
3     100706                University of Alabama in Huntsville   
4     100724                           Alabama State University   
5     100733                University of Alabama System Office   
6     100751                          The University of Alabama   
7     100760                  Central Alabama Community College   
8     100812                            Athens State University   
9     100830                    Auburn University at Montgomery   
10    100858                                  Auburn University   
11    100937                        Birmingham Southern College   
12    101028             Chattahoochee Valley Community College   
13    101073                          Concordia College Alabama   
14    101116                        South University-Montgomery   
15    101143                 Enterprise State Community College   
16    101161                  Coastal Alabama Community College   
17    101189                                Faulkner University   
18    101240                    Gadsden State Community College   
19    101277               New Beginning College of Cosmetology   
20    101286          George C Wallace Community College-Dothan   
21    101295  George C Wallace State Community College-Hance...   
22    101301     George C Wallace State Community College-Selma   
23    101365                      Herzing University-Birmingham   
24    101435                                 Huntingdon College   
25    101453                      Heritage Christian University   
26    101462  J. F. Drake State Community and Technical College   
27    101471                 J F Ingram State Technical College   
28    101480                      Jacksonville State University   
29    101499                  Jefferson Davis Community College   
...      ...                                                ...   
7123  491109             National American University-Watertown   
7124  491118  National American University-Career Point Coll...   
7125  491127     Little Priest Tribal College - Ho Chunk Centre   
7126  491136                         Empire Beauty School-Tampa   
7127  491145                      Empire Beauty School-Lakeland   
7128  491154                Bard College - Holyoke Microcollege   
7129  491163                          Advanced College-Stockton   
7130  491172                               Academy Di Capelli -   
7131  491181                       Galen College of Nursing-ARH   
7132  491190  The Chicago School of Professional Psychology ...   
7133  491206  Olympian Academy of Cosmetology - Internationa...   
7134  491224    Tricoci University of Beauty Culture-Janesville   
7135  491233                       Unlimited Cosmetology School   
7136  491242      Johnny Matthew's Hairdressing Training School   
7137  491251                  The Culinary School of Fort Worth   
7138  491288             University of Wisconsin-Milwaukee Flex   
7139  491297              University of Wisconsin-Parkside Flex   
7140  491303              University of Wisconsin Colleges Flex   
7141  491312                 Arizona State University at Tucson   
7142  491321  Arizona State University - ASU Colleges at Lak...   
7143  491330        Arizona State University at The Gila Valley   
7144  491349                   Arizona State University at Yuma   
7145  491358   Relay Graduate School of Education - San Antonio   
7146  491367  Relay Graduate School of Education - Dallas-Fo...   
7147  491376  Relay Graduate School of Education - Washingto...   
7148  491385                           Wright Institute (The) -   
7149  491394                                  Edge Tech Academy   
7150  491419          Health Career Institute- Lauder

<body>
    <section style="background-color:White; font-family:Georgia;text-align:center">
        <h3 style="font-family:Garamond;">Now that we have all the table setup, we will locate the nearest locations using the seconds part of the coordinate, therefore we will filter by using the degrees and minutes for both, latitude and longitud first. The result will be the ones that less than a minute away from our median reference.
        </h3>
        <hr/>
    </section>
</body>

In [77]:
type(t)

pandas.core.frame.DataFrame

In [78]:
#query = "degreesLongitud=="+str(longDegMean)+str(longMinMean)+" and degreesLatitude =="+str(latDegMean)
minLatD=latDegMean-2
maxLatD=latDegMean+2
minLongD=longDegMean-2
maxLongD=longDegMean+2

minLatM=latMinMean-50
maxLatM=latMinMean+50
minLongM=latDegMean-50
maxLongM=latDegMean+50

query = "(degreesLatitude > "+str(minLatD)+" and degreesLatitude < "+str(maxLatD)+") and ("+"degreesLongitud > "\
+str(minLongD)+" and degreesLongitud < "+str(maxLongD)+") and "+\
"(minutesLatitud > "+str(minLatM)+" and minutesLatitud < "+str(maxLatM)+") and ("+"minutesLongitud > "\
+str(minLongM)+" and minutesLongitud < "+str(maxLongM)+")"
#query = "degreesLatitude > 35 and degreesLatitude < 39"
print(query)
df_filtered = t.query(query)
df_filtered

(degreesLatitude > 35 and degreesLatitude < 39) and (degreesLongitud > -92 and degreesLongitud < -88) and (minutesLatitud > -20 and minutesLatitud < 80) and (minutesLongitud > -13 and minutesLongitud < 87)


UNITID                                             INSTNM  \
1031  146205                               John A Logan College   
1037  146366                                  Kaskaskia College   
1047  146603                  Lewis and Clark Community College   
1107  148821                          Shawnee Community College   
1974  177436                          Four Rivers Career Center   
2019  178767           Stevens-The Institute of Business & Arts   
2032  179308                      Saint Louis Community College   
4794  419271                              St Louis Hair Academy   
5403  446084                       CALC Institute of Technology   
6595  481988  Vatterott College-ex'treme Institute by Nelly-...   
6703  483911                  Creative Touch Cosmetology School   

                                                 IALIAS  \
1031                                                      
1037                                                      
1047                                                      
1107                                                      
1974                                                      
2019                           Patricia Stevens College   
2032                                                      
4794                                                      
5403  CALC|CALC Inst. of Tech.|CALC Ins of Tech|CALC...   
6595                                                      
6703                                                      

                         ADDR         CITY STABBR         ZIP  FIPS  OBEREG  \
1031   700 Logan College Road  Carterville     IL  62918-2500    17       3   
1037         27210 College Rd    Centralia     IL       62801    17       3   
1047          5800 Godfrey Rd      Godfrey     IL       62035    17       3   
1107  8364 Shawnee College Rd        Ullin     IL       62992    17       3   
1974         1978 Image Drive   Washington     MO  63090-4235    29       4   
2019   1521 Washington Avenue  Saint Louis     MO       63103    29       4   
2032       300 South Broadway  Saint Louis     MO  63102-2810    29       4   
4794         3701 Kossuth ave  Saint Louis     MO  63107-1737    29       4   
5403     200A North Center Dr        Alton     IL       62002    17       3   
6595     800 North 3rd Street    St. Louis     MO  63102-2115    29       4   
6703      234 East 3rd Street     Waterloo     IL  62298-1609    17       3   

                           CHFNM      ...                 COUNTYNM CNGDSTCD  \
1031               Dr. Ron House      ...        Williamson County     1712   
1037             Dr. Penny Quinn      ...           Clinton County     1715   
1047              Dale T Chapman      ...           Madison County     1713   
1107  Dr. Peggy Jackson Bradford      ...           Pulaski County     1712   
1974              Robin Kluesner      ...          Franklin County     2903   
2019        Cynthia A. Musterman      ...           St. Louis City     2901   
2032             Jeff L. Pittman      ...           St. Louis City     2901   
4794            Bessie Henderson      ...           St. Louis City     2901   
5403               Fred Albrecht      ...           Madison County     1712   
6595                  Carl Nappa      ...           St. Louis City     2901   
6703           PatriciaCMcDonald      ...            Monroe County     1712   

        LONGITUD   LATITUDE degreesLongitud  minutesLongitud secondsLongitud  \
1031   -89.09021  37.747453             -89               -5             -24   
1037  -89.191723  38.562292             -89              -11             -30   
1047  -90.195552  38.952408             -90              -11             -43   
1107   -89.03352  37.270198             -89               -2               0   
1974  -91.020914  38.547707             -91               -1             -15   
2019  -90.201061   38.63282             -90              -12              -3   
2032  -90.190701   38.62273       

We just got a great subset, but we got 11, let's discard the furthes one

In [79]:
df_filtered.sort_index
df_filtered.sort_values(by=['degreesLongitud'])
result = df_filtered[1:]

<body>
    <section style="background-color:White; font-family:Georgia;text-align:center">
        <h1 style="font-family:Garamond;color:solid #A93226">Results</h1>
        <hr/>
    </section>
</body>

<body>
    <section style="background-color:White; font-family:Georgia;text-align:center">
        <h3 style="font-family:Garamond;">The table below shows the 10 nearest institutions nearby the median point
        </h3>
        <hr/>
    </section>
</body>

In [80]:
result

UNITID                                             INSTNM  \
1037  146366                                  Kaskaskia College   
1047  146603                  Lewis and Clark Community College   
1107  148821                          Shawnee Community College   
1974  177436                          Four Rivers Career Center   
2019  178767           Stevens-The Institute of Business & Arts   
2032  179308                      Saint Louis Community College   
4794  419271                              St Louis Hair Academy   
5403  446084                       CALC Institute of Technology   
6595  481988  Vatterott College-ex'treme Institute by Nelly-...   
6703  483911                  Creative Touch Cosmetology School   

                                                 IALIAS  \
1037                                                      
1047                                                      
1107                                                      
1974                                                      
2019                           Patricia Stevens College   
2032                                                      
4794                                                      
5403  CALC|CALC Inst. of Tech.|CALC Ins of Tech|CALC...   
6595                                                      
6703                                                      

                         ADDR         CITY STABBR         ZIP  FIPS  OBEREG  \
1037         27210 College Rd    Centralia     IL       62801    17       3   
1047          5800 Godfrey Rd      Godfrey     IL       62035    17       3   
1107  8364 Shawnee College Rd        Ullin     IL       62992    17       3   
1974         1978 Image Drive   Washington     MO  63090-4235    29       4   
2019   1521 Washington Avenue  Saint Louis     MO       63103    29       4   
2032       300 South Broadway  Saint Louis     MO  63102-2810    29       4   
4794         3701 Kossuth ave  Saint Louis     MO  63107-1737    29       4   
5403     200A North Center Dr        Alton     IL       62002    17       3   
6595     800 North 3rd Street    St. Louis     MO  63102-2115    29       4   
6703      234 East 3rd Street     Waterloo     IL  62298-1609    17       3   

                           CHFNM      ...               COUNTYNM CNGDSTCD  \
1037             Dr. Penny Quinn      ...         Clinton County     1715   
1047              Dale T Chapman      ...         Madison County     1713   
1107  Dr. Peggy Jackson Bradford      ...         Pulaski County     1712   
1974              Robin Kluesner      ...        Franklin County     2903   
2019        Cynthia A. Musterman      ...         St. Louis City     2901   
2032             Jeff L. Pittman      ...         St. Louis City     2901   
4794            Bessie Henderson      ...         St. Louis City     2901   
5403               Fred Albrecht      ...         Madison County     1712   
6595                  Carl Nappa      ...         St. Louis City     2901   
6703           PatriciaCMcDonald      ...          Monroe County     1712   

        LONGITUD   LATITUDE degreesLongitud  minutesLongitud secondsLongitud  \
1037  -89.191723  38.562292             -89              -11             -30   
1047  -90.195552  38.952408             -90              -11             -43   
1107   -89.03352  37.270198             -89               -2               0   
1974  -91.020914  38.547707             -91               -1             -15   
2019  -90.201061   38.63282             -90              -12              -3   
2032  -90.190701   38.62273             -90              -11             -26   
4794  -90.215765   38.66547             -90              -12             -56   
5403  -90.175979  38.927494             -90              -10             -33   
6595  -90.185221   38.63119             -90              -11              -6   
6703  -90.146261   38.33544             -90               -8             -46   

     degreesLatitud

<body>
    <section style="background-color:White; font-family:Georgia;text-align:center">
        <h3 style="font-family:Garamond;">The image below show in a map where the median is as a green landmark, and as blue the 10 nearby institutions.
        </h3>
        <hr/>
    </section>
</body>

![title](result.png)